stages:
  - lint
  - build

variables:
  GIT_SSL_NO_VERIFY: "true"

lint:
  stage: lint
  image: node:20
  script:
    - npm install
    - npm run lint
  only:
    - main

build:
  stage: build
  image: node:20
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - main